[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r request.txt"]

[phases.start]
cmds = ["python3 afkbot.py"]

[start]
cmd = "python3 afkbot.py"
